export async function GET() {
  const content = `# Minka Works

Practical AI for Latin American businesses.

## About

Minka Works builds simple, practical tools for teams that still run on WhatsApp, spreadsheets, notebooks, and manual workflows.

## Main Pages

- https://minkaworks.com/es
- https://minkaworks.com/en

## Contact Form

The contact form posts to the /api/contact endpoint, which forwards leads to Google Sheets through Google Apps Script.

## Deployment Notes

- The app redirects the root path based on the browser language.
- Cloudflare handles the canonical domain redirects and robots.txt.
- The sitemap is generated by Next.js.
`

  return new Response(content, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=0, must-revalidate',
    },
  })
}
